Updating to Play3 & Pekko
Jyllands-Posten/play-prometheus-filters pull request #50
Opened 2023-12-11 17:58 UTC by mveeprojects

Raising as a draft as I'm working through some issues in the tests but I wanted to raise this for your consideration to help support Play3 applications including the move from Akka to Pekko.

2024-01-12 15:17 UTC, mveeprojects commented
@renevangsgaardjp are you able to review this? Saw you were the last person to merge into this repo.

2024-01-17 15:22 UTC, schonbachler commented
I am also very thankful if these changes are integrated.

2024-02-09 08:59 UTC, DraganRaicici commented
@mveeprojects Hi there. As far as I know, no one from us actually has active eyes on this project. My team has some projects in which we're updating to Play 3 & Pekko and I am now aware of your request changes. I will make sure someone takes a look at this, since others are also interested in these updates

2024-03-20 15:09 UTC, DraganRaicici requested changes
Can we bump the version number in the ReadMe to reflect the latest soon-to-be release?

2024-03-21 08:48 UTC, merged